version: '3'
services:
  app:
    build: .
    ports:
      - 3000:3000
    container_name: batalha-naval-app
    environment:
      REDIS_HOST: batalha-naval-redis
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:alpine
    container_name: batalha-naval-redis
